package com.bank.bian.employeedatamanagement;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Employee Data Management
 *
 * Business Area:      Business Support
 * Business Domain:    Human Resources
 * Functional Pattern: Maintain
 * Asset Type:         Employee Record
 * Control Record:     Employee Record Maintenance Agreement
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Employee Data Management — BIAN Semantic API")
                .description("Service Domain 'Employee Data Management' (Maintain pattern) "
                        + "operating on the 'Employee Record Maintenance Agreement' control record.")
                .version("0.1.0"));
    }
}
